small fixes, add options template to newsh

diff --git a/newsh b/newsh
--- a/newsh
+++ b/newsh
@@ -24,8 +24,19 @@ if [[ "\$#" -ne ${#args[@]} ]]; then
     echo "Illegal number of parameters" >&2
     exit 1
 fi
+while getopts "d" opt; do
+    case \$opt in
+	d)
+	    unset GTEST_FILTER
+	    exit 0;
+	    ;;
+	\?)
+	    echo "Invalid option: -\$OPTARG" >&2
+	    ;;
+    esac
+done
 EOM
 
 # Setup the rest
 chmod +x "$filename"
-vim "$filename"
+nvim "$filename"
